import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Toaster } from "sonner";
import UserProvider from "@/providers/userProvider";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "AstraPages - Stellar AI Website Generator",
  description: "Your landing page, generated by AstraPages",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${outfit.className} antialiased`}
        >
          <UserProvider>
            {children}
            <Toaster />
          </UserProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
